<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>Unidot.NativeHost</AssemblyName>
    <RootNamespace>Unidot.NativeHost</RootNamespace>
    <PlatformTarget>x64</PlatformTarget>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../Shared/UnityPlayerValidation.cs" Link="UnityPlayerValidation.cs" />
  </ItemGroup>
</Project>
