using System.Text.Json;
using System.Xml.Linq;

namespace Unidot;

internal static class LauncherGenerator
{
    public static string ProductName(Configuration config)
    {
        if (!string.IsNullOrWhiteSpace(config.ProductName)) return config.ProductName.Trim();
        var player = PlayerLayout.Discover(config.Player);
        var path = Path.Combine(player.DataDirectory, "app.info");
        if (File.Exists(path))
        {
            var lines = File.ReadAllLines(path);
            if (lines.Length > 1 && !string.IsNullOrWhiteSpace(lines[1])) return lines[1].Trim();
        }
        return Path.GetFileNameWithoutExtension(player.Executable);
    }

    public static string SolutionPath(Configuration config)
    {
        var invalid = Path.GetInvalidFileNameChars().Concat(['/', '\\', ':', '"', '\r', '\n']).ToHashSet();
        var name = new string(ProductName(config).Select(c => invalid.Contains(c) ? '_' : c).ToArray()).Trim().TrimEnd('.');
        if (name.Length == 0) name = "Game";
        // Unity 2022 WinPlayerPrerequisiteChecks treats <ProductName>.sln as a native VS build marker.
        return Path.Combine(config.Directory, name + ".Unidot.sln");
    }

    public static void MigrateConflictingSolution(Configuration config)
    {
        var solution = SolutionPath(config);
        var name = Path.GetFileName(solution);
        var oldName = name[..^".Unidot.sln".Length] + ".sln";
        var oldPath = Path.Combine(config.Directory, oldName);
        if (!File.Exists(oldPath)) return;
        var text = File.ReadAllText(oldPath);
        if (!text.Contains("# Generated by Unidot", StringComparison.Ordinal) ||
            !text.Contains(ProjectGenerator.GuidFor("Unidot.Generated.Launcher"), StringComparison.Ordinal))
        {
            Console.Error.WriteLine($"Warning: existing user/native solution preserved at {oldPath}; Unity may refuse to overwrite this build directory.");
            return;
        }
        var destination = Path.Combine(config.GeneratedDirectory, "legacy-solutions", oldName);
        if (File.Exists(destination)) destination = Path.Combine(config.GeneratedDirectory, "legacy-solutions", Path.GetFileNameWithoutExtension(oldName) + "-" + Guid.NewGuid().ToString("N")[..8] + ".sln");
        Directory.CreateDirectory(Path.GetDirectoryName(destination)!);
        File.Move(oldPath, destination);
        Console.WriteLine($"Moved generated solution out of Unity's build marker path: {destination}");
    }

    public static void Generate(Configuration config)
    {
        var directory = Path.Combine(config.GeneratedDirectory, "Launcher");
        var project = new XElement("Project", new XAttribute("Sdk", "Microsoft.NET.Sdk"),
            new XElement("PropertyGroup",
                new XElement("OutputType", "Exe"), new XElement("TargetFramework", "net8.0"),
                new XElement("ImplicitUsings", "enable"), new XElement("Nullable", "enable"),
                new XElement("AssemblyName", "Launcher"), new XElement("RootNamespace", "Launcher"),
                new XElement("EnableDefaultCompileItems", "false"), new XElement("IsPackable", "false"),
                new XElement("RunWorkingDirectory", config.Directory)),
            new XElement("ItemGroup", new XElement("Compile", new XAttribute("Include", "Program.cs"))));
        ProjectGenerator.WriteIfChanged(Path.Combine(directory, "Launcher.csproj"), new XDocument(project).ToString());
        var configFile = config.FilePath ?? Path.Combine(config.Directory, "unidot.json");
        var literal = JsonSerializer.Serialize(configFile);
        var workingDirectory = JsonSerializer.Serialize(config.Directory);
        var source = $$"""
            // Generated by Unidot. Launcher owns the CLI lifetime; Unity stays a child of that session.
            using System.Diagnostics;

            using var cancellation = new CancellationTokenSource();
            Console.CancelKeyPress += (_, e) => { e.Cancel = true; cancellation.Cancel(); };
            var start = new ProcessStartInfo("unidot")
            {
                WorkingDirectory = {{workingDirectory}},
                UseShellExecute = false,
                RedirectStandardOutput = true,
                RedirectStandardError = true
            };
            start.ArgumentList.Add("run");
            start.ArgumentList.Add("--config");
            start.ArgumentList.Add({{literal}});
            start.ArgumentList.Add("--parent-pid");
            start.ArgumentList.Add(Environment.ProcessId.ToString());
            foreach (var argument in args) start.ArgumentList.Add(argument);
            try
            {
                using var process = Process.Start(start) ?? throw new InvalidOperationException("Could not start unidot.");
                async Task PumpAsync(StreamReader reader, TextWriter output)
                {
                    while (await reader.ReadLineAsync(cancellation.Token) is { } line)
                        await output.WriteLineAsync(line);
                }
                var output = Task.WhenAll(PumpAsync(process.StandardOutput, Console.Out), PumpAsync(process.StandardError, Console.Error));
                try { await process.WaitForExitAsync(cancellation.Token); await output; return process.ExitCode; }
                catch (OperationCanceledException)
                {
                    // Exiting Launcher is observed by unidot's parent watcher, which closes its owned Player.
                    Console.WriteLine("Launcher stopping; closing the Unidot session.");
                    return 130;
                }
            }
            catch (System.ComponentModel.Win32Exception error)
            {
                Console.Error.WriteLine("Cannot find unidot on PATH. Install Net.BITKit.Unidot as a global .NET Tool. " + error.Message);
                return 1;
            }
            """;
        ProjectGenerator.WriteIfChanged(Path.Combine(directory, "Program.cs"), source + Environment.NewLine);
        ProjectGenerator.WriteIfChanged(Path.Combine(directory, "Properties", "launchSettings.json"), JsonSerializer.Serialize(new
        {
            profiles = new Dictionary<string, object>
            {
                ["Launcher"] = new { commandName = "Project", workingDirectory = config.Directory }
            }
        }, Configuration.JsonOptions));
        var riderProject = "$PROJECT_DIR$/" + Path.GetRelativePath(config.Directory, Path.Combine(directory, "Launcher.csproj")).Replace('\\', '/');
        var rider = new XElement("component", new XAttribute("name", "ProjectRunConfigurationManager"),
            new XElement("configuration", new XAttribute("default", "false"), new XAttribute("name", "Launcher"),
                new XAttribute("type", "DotNetProject"), new XAttribute("factoryName", ".NET Project"),
                new XElement("option", new XAttribute("name", "PROJECT_PATH"), new XAttribute("value", riderProject)),
                new XElement("option", new XAttribute("name", "WORKING_DIRECTORY"), new XAttribute("value", config.Directory)),
                new XElement("option", new XAttribute("name", "PROGRAM_PARAMETERS"), new XAttribute("value", "")),
                new XElement("option", new XAttribute("name", "PASS_PARENT_ENVS"), new XAttribute("value", "1")),
                new XElement("option", new XAttribute("name", "USE_EXTERNAL_CONSOLE"), new XAttribute("value", "0")),
                new XElement("method", new XAttribute("v", "2"), new XElement("option", new XAttribute("name", "Build")))));
        var riderPath = Path.Combine(config.Directory, ".run", "Launcher.run.xml");
        if (File.Exists(riderPath) && !File.ReadAllText(riderPath).Contains("Generated by Unidot", StringComparison.Ordinal))
            Console.Error.WriteLine($"Warning: existing user Rider configuration preserved: {riderPath}");
        else ProjectGenerator.WriteIfChanged(riderPath, new XDocument(new XComment("Generated by Unidot"), rider).ToString());
    }
}
